Django/just_urls/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('postlist/', views.postList, name='post_list'),
    path('postlist/<slug:tag_slug>/', views.postList, name='post_list_tag'),
    # path('postlist/', views.PostListView.as_view(), name='post_list'),
    path('postdetail/<slug:slug>/<int:pk>/', views.postdetail, name='post_detail'),
    path('account-form/', views.userAccount, name='account_form'),
    path('share-post/<int:post_id>/', views.sharePost, name='share-post'),
    path('regroup/', views.regroup, name='regroup'),
    path('search/', views.search, name='search'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change-password/', views.change_password, name='change-password'),
]

Django/just_urls/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact-us/', views.contactUs, name='contact_us')
]

Django/just_urls/just_urls/urls.py
from django.contrib import admin
from django.urls import path, include

# app_name = 'default'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
]

Django/just_urls/home/models.py
from django.db import models

# Create your models here.

Django/just_urls/home/forms.py
from django import forms


class ContactUsForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea, required=True, label='Message')
    name = forms.CharField(max_length=25, required=True, label='Full name')
    email = forms.EmailField(required=True, label='Email')
    subject = forms.CharField(max_length=25, required=True, label='Subject')
    phone = forms.CharField(max_length=11, required=False, label='Phone Number')

Django/just_urls/home/views.py
from django.shortcuts import render
from .forms import ContactUsForm
from django.http import HttpResponse
from django.core.mail import send_mail
# Create your views here.


def index(request):
    return render(request, 'home/index.html', {'link': request.build_absolute_uri('admin/')})


def contactUs(request):
    sent = False
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = cd['subject']
            name = cd['name']
            email = cd['email']
            phone = cd['phone']
            message = cd['message']
            msg = f'name:{name}\nphone:{phone}\nemail:{email}\nmessage:\n{message}'
            from_email = 'en.ansari@outlook.com'
            to = 'rahmat2022a@gmail.com'
            sub = f'from contact of site: {subject}'
            sent = send_mail(sub, msg, from_email, [to], fail_silently=True)
            return render(request, 'home/forms/contact-us.html', {'form': form, 'sent': sent})
    form = ContactUsForm()
    return render(request, 'home/forms/contact-us.html', {'form': form, 'sent': sent})

Django/just_urls/templates/home/forms/contact-us.html
{% extends 'blog/parent/base.html' %}
{% load static %}
{% block title %}contact us{% endblock %}
{% block content %}
    <h1 style="color: navy; margin-right: auto">Contact US</h1>
    {% if sent %}
        <p style="color: green">Message Sent Successfully!</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        Full name:
        <input type="text" name="name" required maxlength="25">
        <br><br>
        Email:
        <input type="email" name="email" required>
        <br><br>
        Phone Number:
        <input type="text" name="phone" maxlength="11">
        <br><br>
        Subject:
        <select name="subject" required>
            <option value="critics and suggestions">Critics and Suggestions</option>
            <option value="complaints">Complaints</option>
        </select>
        <br><br>
        Message Text:
        <textarea style="width: 400px; height: 300px; resize: none" name="message" required>{% lorem 2 random %}</textarea>
        <br><br>
        <input type="submit" value="send" style="background-color: greenyellow">

    </form>

    <a href="{% url "home:index" %}">
        back
    </a>

    {% if form.errors %}
        fix above errors:
        <br>
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                    <br>
                {% endfor %}
            {% endif %}
        {% endfor %}
        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}
    {% endif %}

{% endblock %}