Django/just_urls/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('postlist/', views.postList, name='post_list'),
    path('postlist/<slug:tag_slug>/', views.postList, name='post_list_tag'),
    # path('postlist/', views.PostListView.as_view(), name='post_list'),
    path('postdetail/<slug:slug>/<int:pk>/', views.postdetail, name='post_detail'),
    path('account-form/', views.userAccount, name='account_form'),
    path('share-post/<int:post_id>/', views.sharePost, name='share-post'),
    path('regroup/', views.regroup, name='regroup'),
    path('search/', views.search, name='search'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change-password/', views.change_password, name='change-password'),
]

Django/just_urls/just_urls/urls.py
from django.contrib import admin
from django.urls import path, include

# app_name = 'default'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
]

Django/just_urls/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.


class PostManager(models.Manager):
    def Y(self, year):
        return self.filter(publish__year=year)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
    # objects = models.Manager()
    objects = PostManager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug, 'pk': self.id})

    def __str__(self):
        return self.title


class Account(models.Model):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    phone = models.CharField(max_length=11, null=True, blank=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default='female')
    address = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    age = models.PositiveIntegerField(default=0, null=True, blank=True)
    # birthday

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {0} on {1}'.format(self.name, self.post)

Django/just_urls/blog/forms.py
from django import forms
from .models import *


class AccountForm(forms.Form):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    first_name = forms.CharField(max_length=25, label='First Name')
    last_name = forms.CharField(max_length=50, label='Last Name')
    phone = forms.CharField(max_length=11, required=True, label='Phone Number')
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect, label='Gender')
    address = forms.CharField(max_length=250, widget=forms.Textarea, label='Address')
    age = forms.IntegerField(label='Age')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError('phone number must be numeric!')
            else:
                return phone

    def clean_age(self):
        age = self.cleaned_data['age']
        if age:
            if age < 0:
                raise forms.ValidationError('age can not be negative!')
            else:
                return age


class ShareForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'name-class'}), required=True, label='Message')
    name = forms.CharField(widget=forms.TextInput, max_length=25, required=True, label='Full name')
    to = forms.EmailField(required=True, label='Email')


class MyFor(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'titleClass'
            })
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')
        widgets = {
            'body': forms.Textarea(attrs={'class': 'body-of-comment'})
        }


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(), label='old password')
    new_password1 = forms.CharField(widget=forms.PasswordInput(), label='new password')
    new_password2 = forms.CharField(widget=forms.PasswordInput(), label='repeat of new password')

    def clean_new_password1(self):
        new_password = self.cleaned_data.get('new_password1')
        if len(new_password) < 8:
            raise forms.ValidationError('Your Password must be 8 character minimum!')
        return new_password

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 != password2:
            raise forms.ValidationError('new password and its repeat isn\'t equal!')
        return password2

Django/just_urls/blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, Q
from django.db.models.functions import Greatest
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag

from .forms import AccountForm, ShareForm, CommentForm, LoginForm, ChangePasswordForm
from .models import Post, Account


def index(request):
    return HttpResponse("Hello, This is my first django Project!")


def postList(request, tag_slug=None):
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    packet = {
        'posts': posts,
        'page': page,
        'tag': tag,
    }
    return render(request, 'blog/post/index.html', packet)


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/post/index.html'


def postdetail(request, slug, pk):
    post = get_object_or_404(Post, status='published', slug=slug, id=pk)
    # comments = Comment.objects.filter(post=post)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(s_count=Count('tags')).order_by('-s_count', '-publish')[:2]

    packet = {
        'post': post,
        'cm': comments,
        'ncm': new_comment,
        'cm_form': comment_form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/post/postdetail.html', packet)


def userAccount(request):
    user = request.user
    try:
        account = Account.objects.get(user=user)
    except:
        account = Account.objects.create(user=user)
    if request.POST:
        form = AccountForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            account.gender = form.cleaned_data['gender']
            account.address = form.cleaned_data['address']
            account.age = form.cleaned_data['age']
            account.phone = form.cleaned_data['phone']
            user.save()
            account.save()
            return redirect('blog:index')
        else:
            return render(request, 'blog/forms/account_form.html', {'form': form, 'account': account})
    form = AccountForm()
    return render(request, 'blog/forms/account_form.html', {'form': form, 'account': account})


def sharePost(request, post_id):
    post = get_object_or_404(Post, status='published', id=post_id)
    sent = False
    if request.method == 'POST':
        form = ShareForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{0} invited you to read {1}'.format(cd['name'], post.title)
            to = cd['to']
            message = cd['message']
            msg = f"{cd['name']} invited you to reading {post.title} post in above link:\n{post_url}\n{message}"
            from_email = 'en.ansari@outlook.com'
            sent = send_mail(subject, msg, from_email, [to], fail_silently=True)
            return render(request, 'blog/forms/share-post.html', {'form': form, 'sent': sent, 'post': post})
    form = ShareForm()
    return render(request, 'blog/forms/share-post.html', {'form': form, 'sent': sent, 'post': post})


def regroup(request):
    packet = [
        {'name': 'Rahmat', 'age': 21, 'weight': 80},
        {'name': 'Amir', 'age': 14, 'weight': 60},
        {'name': 'Reza', 'age': 50, 'weight': 90},
        {'name': 'Hossein', 'age': 21, 'weight': 70},
        {'name': 'Narges', 'age': 14, 'weight': 50},
    ]
    text = "Hello"
    return render(request, 'blog/post/regroup.html', {'packet': packet, 'text': text})


def search(request):
    if request.method == 'GET':
        query_name = request.GET.get('search-input')
        if query_name:
            request.session['query-session'] = query_name
        else:
            try:
                query_name = request.session['query-session']
            except:
                query_name = ''

        # result1 = Post.published.filter(body__search=query_name)
        # search_vector = SearchVector('body', weight='B') + SearchVector('title', weight='A')
        # search_query = SearchQuery(query_name)
        # search_rank = SearchRank(search_vector, search_query)
        # posts = Post.published.annotate(
        #     # search=search_vector,
        #     rank=search_rank
        # ).filter(rank__gte=0.3).order_by('-rank')

        # posts = Post.published.filter(Q(body__contains=query_name) | Q(title__contains=query_name))

        sim_search = Greatest(
            TrigramSimilarity('body', query_name),
            TrigramSimilarity('title', query_name)
        )
        posts = Post.published.annotate(sim=sim_search).filter(sim__gt=0.0).order_by('-sim')
        paginator = Paginator(posts, 2)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/post/index.html', {'posts': posts, 'page': page})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home:index')
                else:
                    return HttpResponse('Your Account is de-active!')
            else:
                return HttpResponse('username or password is incorrect!')
    else:
        form = LoginForm()
    return render(request, 'blog/forms/account/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home:index')


@login_required(login_url='home:index')
def change_password(request):
    if request.method == 'POST':
        user = request.user
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            old_password = cd['old_password']
            new_password1 = cd['new_password1']
            new_password2 = cd['new_password2']
            if not user.check_password(old_password):
                return HttpResponse('your old password is incorrect!')
            elif new_password1 != new_password2:
                return HttpResponse('your new passwords is not equal!')
            else:
                user.set_password(new_password1)
                user.save()
                login(request, user)
                # return HttpResponse('your password is changed successfully!')
                return redirect('home:index')
    else:
        form = ChangePasswordForm()
    return render(request, 'blog/forms/account/change_password.html', {'form': form})

Django/just_urls/templates/blog/post/index.html
{% extends 'blog/parent/base.html' %}
{% load static %}
{% block title %}list{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}
{% block content %}
    <h1 class="test"><a href="{% url 'blog:post_list' %}">List of Posts!</a></h1>
    {% if tag %}
        posts filtered by
        <span style="color: red">{{ tag.name }}</span>
        (<a href="{% url 'blog:post_list' %}">remove</a>)
    {% endif %}
    {% for post in posts %}
        <div style="border: solid 1px navy; width: 300px">
        <a href="{{ post.get_absolute_url }}">
            <h3>{{ post.title }} : {{ post.author }}</h3>
        </a>
            <div style="color: darkred">
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_tag' tag.slug %}">{{ tag.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
        </div>
        <br>
    {% empty %}
        There is not any posts!<br><br>
    {% endfor %}
    <a href="{% url "home:index" %}">
        back
    </a>
{#    <img src="{% static 'img/outside.jpg' %}">#}
    {% include 'blog/partials/pagination.html' with page=posts %}
{#    {% include 'blog/partials/pagination.html' with page=page_obj %}#}
{% endblock %}

Django/just_urls/templates/blog/post/last-posts.html
<div>
    last posts:<br>
    {% for post in posts %}
        <a href="{% url 'blog:post_detail' post.slug post.id %}">{{ post.title }}: {{ post.publish }}</a>
        <br>
    {% empty %}
        There is not any posts!
    {% endfor %}
</div>

Django/just_urls/templates/blog/post/postdetail.html
{% extends 'blog/parent/base.html' %}
{% block title %}Detail{% endblock %}
{% load blog_tags %}
{% block content %}
    <h2>
        {{ post.title }}
    </h2>
    <i>
        written by: {{ post.author }}
    </i>
    <div style="width: 600px">
        <p>
            context: <br>
    {#        {{ post.body | linebreaks | truncatewords:3 }}#}
            {{ post.body | linebreaks }}
        </p>
    </div>
    <hr>
    <p>
        published in {{ post.publish }}
    </p>
    <a href="{% url 'blog:share-post' post.id %}">
        <p>share by email</p>
    </a>
    <br>
    <a href="{% url "blog:post_list" %}">
        back
    </a>
    <br><br>
    <div class="comment">
        <div class="new-comment">
            <h3 style="align-content: center">New Comment</h3>
            <form method="post">
                {% csrf_token %}
                {{ cm_form.as_p }}
                {% if ncm %}
                    <p style="color: green">
                        Comment Submitted Successfully!
                    </p>
                {% endif %}
                <input type="submit" value="comment">
            </form>
        </div>
        <br>
        {% with cm.count as count %}
            this post have {{ count }} comment
            <br>
            {% for comment in cm %}
                <div style="border: solid 1px green">
                {{ forloop.counter }}- {{ comment.name }}:
                <br>
                {{ comment.body }}
                </div>
                <br>
            {% empty %}
                There is no comment!
            {% endfor %}
        {% endwith %}
    </div>
    <div>
        Tags:
        {% for tag in post.tags.all %}
            {{ tag.name }}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </div>
    <hr>
    <div>
        similar posts:
        <br>
        {% for sm in similar_posts %}
            <a href="{% url 'blog:post_detail' sm.slug sm.id %}">{{ sm.title }}</a>
            <br>
        {% empty %}
            There is not any posts!
        {% endfor %}
    </div>
    <br>
    {% last_posts %}
{% endblock %}

Django/just_urls/templates/blog/post/regroup.html
{% extends 'blog/parent/base.html' %}
{% load blog_tags %}
{% block title %}Detail{% endblock %}
{% block content %}
    {% spaceless %}
        {% regroup packet|dictsort:"age" by age as g_list %}
        <ul>
            {% for age in g_list %}
                <li>
                    {{ age.grouper }}
                    <ul>
                        {% for item in age.list %}
                            <li>{{ item.name }}: {{ item.weight }}</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endspaceless %}
    <div>
        {{ text|markdown }}
    </div>
{% endblock %}